[project]
name = "readme-generator"
description = "Tool zur automatischen README-Generierung für Coding-Projekte mit Ollama-Analyse."
version = "0.1.0"
authors = ["Dein Name <email@example.com>"]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "ollama",
]

